name: Run Notebooks

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter papermill kaggle google-colab

      - name: Configure Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
            mkdir -p ~/.kaggle
            echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
            chmod 600 ~/.kaggle/kaggle.json

      - name: Run notebooks
        run: |
          for notebook in examples/qwen3_example.ipynb; do
              if [ -f "$notebook" ]; then
                  echo "Running $notebook"
                  papermill "$notebook" "${notebook%.ipynb}_output.ipynb"
              fi
          done

      - name: Upload notebook outputs
        uses: actions/upload-artifact@v4
        with:
          name: notebook-outputs
          path: examples/*_output.ipynb
